# Generated by Django 5.0.3 on 2024-03-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_group_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
