# Generated by Django 5.0.3 on 2024-03-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_conversation_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_notification',
            field=models.BooleanField(default=False),
        ),
    ]
